### ISSUE TITLE
react-native-windows and auto-linking

### ISSUE THREAD

**Issue by vvsamin** [renative-org/renative#762]
As I can see autolinking is set to "false" for react-native-windows/cli. If I set the "autolink" property to "true" for the "windows" platform in the renative config, then the build crashes at the autolinking stage (problems with paths). How can I link packages such as "async-storage" or "react-native-video"?

**Comment by vvsamin** [comment]
@RicardasN can you help me with this?

**Comment by RicardasN** [comment]
> @RicardasN can you help me with this?


At the moment the react-native-windows engine was added as a sort of alpha test if it would work. React-navigation seemed to work straight out of the box, the focusing of elements on Xbox using gamepad required some things enabled before it started to work, however, due to other priorities the experiment was left at that stage, with quite a lot still in TODO.

What still needs to be done?:
- General Windows OS support as you need to be using windows to build React Native Windows apps (you may have noticed sometimes bundler fails to start, AndroidTV does not seem to connect to bundler for some reason, exporting Android builds also has some issues if I remember, other platforms have some other issues as well)
- Fixing auto-linking or enabling manual linking for packages, perhaps using [this guide](https://microsoft.github.io/react-native-windows/docs/native-modules-using)
- C# builds were never investigated, I would not be surprised if you set `language: "cs"` that something would crash or not work as expected
- Signing applications, something you would want to do in production is not yet supported by ReNative, you'd have to manually go to the folder and sign the app using your certificate ([MS Sign Tool](https://docs.microsoft.com/en-us/windows/msix/package/sign-app-package-using-signtool)).
- Xbox navigation works, however, there is no way implemented for focus behavior control, meaning you have to hope everything works out of the box, which is definitely not ideal.
(And these are just things I have discovered so far, I am sure there's more)

To answer your question linking the native projects as described in the guide I linked on the first point probably would work in your case, for now, however running the app with `-r` flag would reset the whole project and with no auto-linking, you'd have to manually link all the projects again... 
If you have the time to fix any of these things PR on ReNative is highly appreciated, if not, then I will try to look into solving these problems at some point, when other workload lightens

**Comment by vvsamin** [comment]
@RicardasN Thank you for your answer and thank you for your contribution to the ReNative project.
I will try to fix this problem and if something works out I will add PR.

**Comment by mihaiblaga89** [comment]
considering this closed for now, if something else comes up please reopen it.
